In [1]:
import torch 
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()


In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer(),
)


In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-10, grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.0233, -1.0852, -0.5977],
        [ 1.2797, -0.6505, -0.2845],
        [ 1.3229,  0.7770, -0.9501],
        [-0.7441,  1.5721, -1.6813],
        [ 0.2144,  1.0895, -0.3440]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[0.8552, 0.9105, 0.0000],
        [0.6654, 0.9960, 0.0000]])

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[10.9139],
        [ 6.0973]])