In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))

X = torch.rand(2, 20)
net(X)

tensor([[ 0.1708, -0.0852,  0.0527, -0.0558,  0.2434,  0.0512,  0.0382, -0.0862,
          0.0806,  0.1009],
        [ 0.2474, -0.0377,  0.1063, -0.0928,  0.2983,  0.0765, -0.0737, -0.0550,
          0.0144, -0.0145]], grad_fn=<AddmmBackward0>)

In [3]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)

    def forward(self, X):
        # F.relu为ReLU的函数版本
        return self.out(F.relu(self.hidden(X)))

In [4]:
net = MLP()
net(X)

tensor([[ 0.0510,  0.0500, -0.1669, -0.3376,  0.0028, -0.0305, -0.1285,  0.1660,
         -0.0181, -0.0375],
        [ 0.0152,  0.1143, -0.0213, -0.0940,  0.0548,  0.0313,  0.0910,  0.1114,
         -0.0230, -0.1196]], grad_fn=<AddmmBackward0>)

In [5]:
class MySequential(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for idx, module in enumerate(args):
            self._modules[str(idx)] = module
    
    def forward(self, X):
        for block in self._modules.values():
            X = block(X)
        return X

In [6]:
net = MySequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))
net(X)

tensor([[-0.1425, -0.1098,  0.2155, -0.1580,  0.1657,  0.1275,  0.0162,  0.0815,
          0.1724, -0.2864],
        [-0.0266, -0.0918,  0.2309, -0.1065,  0.1786,  0.0286, -0.0061,  0.0556,
          0.2145, -0.2237]], grad_fn=<AddmmBackward0>)