In [1]:
import torch
from d2l import torch as d2l

In [2]:
X, W_xh = torch.normal(0, 1, (3, 1)), torch.normal(0, 1, (1, 4))
H, W_hh = torch.normal(0, 1, (3, 4)), torch.normal(0, 1, (4, 4))
torch.matmul(X, W_xh) + torch.matmul(H, W_hh)

tensor([[-0.2836, -2.8661, -1.8065,  1.0498],
        [-0.8673, -2.6392, -2.9161,  3.3963],
        [ 0.0354, -2.9665, -0.4827,  2.4485]])

In [4]:
print(X)
print(H)
print(torch.cat((X, H), 1))

tensor([[-0.0492],
        [-1.2122],
        [ 1.3159]])
tensor([[-0.9700, -1.1096, -0.1299,  0.6139],
        [ 0.4444, -2.3026,  0.9077,  0.1287],
        [-0.4405, -0.6246,  0.0934,  0.0842]])
tensor([[-0.0492, -0.9700, -1.1096, -0.1299,  0.6139],
        [-1.2122,  0.4444, -2.3026,  0.9077,  0.1287],
        [ 1.3159, -0.4405, -0.6246,  0.0934,  0.0842]])


In [5]:
# (X, H) matmul (W_xh, W_hh)^T = XW_xh + HW_hh
torch.matmul(torch.cat((X, H), 1), torch.cat((W_xh, W_hh), 0))

tensor([[-0.2836, -2.8661, -1.8065,  1.0498],
        [-0.8673, -2.6392, -2.9161,  3.3963],
        [ 0.0354, -2.9665, -0.4827,  2.4485]])